---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: addons
spec:
  components:
    - name: git-addons
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/zozores/vela-gitops
        git:
          branch: main
        path: ./addons