apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cnpg
  namespace: base
  labels:
    project: base
spec:
  components:
    - name: cnpg
      type: helm
      properties:
        repoType: helm
        url: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        version: 0.23.2
        namespace: cnpg-system

    - name: cnpg-cluster
      type: raw
      dependsOn:
        - cnpg
      properties:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: cnpg
          namespace: cnpg-system
        spec:
          instances: 1
          storage:
            size: 20Gi
            storageClass: local-path
            bootstrap:
              initdb:
                database: app
                owner: app
                secret:
                  name: cnpg-app

  policies:
  - name: cnpg-sampa
    properties:
      clusters:
      - sampa
      namespace: cnpg-system
    type: topology

  workflow:
    steps:
    - meta:
        alias: Deploy To cnpg-sampa
      name: cnpg-sampa
      properties:
        policies:
        - cnpg-sampa
      type: deploy