apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: external-secrets
  namespace: base
spec:
  components:
    - name: external-secrets
      type: helm
      properties:
        repoType: helm
        url: https://charts.external-secrets.io
        chart: external-secrets
        version: 0.16.1
        namespace: external-secrets

    - name: secret-store
      type: raw
      dependsOn:
        - external-secrets
      properties:
        apiVersion: external-secrets.io/v1beta1
        kind: ClusterSecretStore
        metadata:
          name: infisical
        spec:
          provider:
            infisical:
              auth:
                universalAuthCredentials:
                  clientId:
                    key: clientId
                    namespace: default
                    name: infisical-auth-credentials
                  clientSecret:
                    key: clientSecret
                    namespace: default
                    name: infisical-auth-credentials
              secretsScope:
                projectSlug: taotec-iv-vb
                environmentSlug: prod
                secretsPath: /
              hostAPI: https://app.infisical.com

  policies:
  - name: external-secrets-local
    properties:
      clusters:
      - local
      namespace: external-secrets
    type: topology
  - name: external-secrets-sampa
    properties:
      clusters:
      - sampa
      namespace: external-secrets
    type: topology
    
  workflow:
    steps:
    - meta:
        alias: Deploy To external-secrets-local
      name: external-secrets-local
      properties:
        policies:
        - external-secrets-local
      type: deploy
    - meta:
        alias: Deploy To external-secrets-sampa
      name: external-secrets-sampa
      properties:
        policies:
        - external-secrets-sampa
      type: deploy