apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tailscale-operator
  namespace: base
spec:
  components:
    - name: tailscale-auth
      type: raw
      properties:
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: tailscale-auth
        spec:
          refreshInterval: 0.03m
          secretStoreRef:
            kind: ClusterSecretStore
            name: oracle
          target:
            name: tailscale-auth
            creationPolicy: Owner
          data:
            - secretKey: values.yaml
              remoteRef:
                key: tailscale_values

    - name: tailscale-operator
      type: helm
      dependsOn:
        - tailscale-auth
      properties:
        repoType: helm
        url: https://pkgs.tailscale.com/helmcharts
        chart: tailscale-operator
        version: 1.82.0
        namespace: tailscale
        valuesFrom:
          - kind: Secret
            name: tailscale-auth

  policies:
  - name: tailscale-local
    properties:
      clusters:
      - local
      namespace: tailscale
    type: topology
  - name: tailscale-sampa
    properties:
      clusters:
      - sampa
      namespace: tailscale
    type: topology
    
  workflow:
    steps:
    - meta:
        alias: Deploy To tailscale-local
      name: tailscale-local
      properties:
        policies:
        - tailscale-local
      type: deploy
    - meta:
        alias: Deploy To tailscale-sampa
      name: tailscale-sampa
      properties:
        policies:
        - tailscale-sampa
      type: deploy