---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: base
  namespace: default
spec:
  components:
    - name: git-base
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/zozores/vela-gitops
        git:
          branch: main
        path: ./base