---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: miniflux
  namespace: default
spec:
  project: default
  components:
    - name: git-miniflux
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/zozores/vela-gitops
        git:
          branch: main
        path: ./apps/miniflux
