apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  components:
    - name: external-secrets
      type: helm
      properties:
        repoType: helm
        url: https://charts.external-secrets.io
        chart: external-secrets
        version: 0.16.1
        namespace: external-secrets

    - name: secret-store
      type: raw
      dependsOn:
        - external-secrets
      properties:
        apiVersion: external-secrets.io/v1beta1
        kind: ClusterSecretStore
        metadata:
          name: oracle
        spec:
          provider:
            oracle:
              vault: ocid1.vault.oc1.sa-saopaulo-1.ffua45bdaacnc.abtxeljriv57fvxdpmosqg5letcgqvgqs4b63rhzqzdulxexfghp4ny7ik5a
              region: sa-saopaulo-1
              principalType: InstancePrincipal