---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets/namespace.yaml
  - tailscale/namespace.yaml
  - ingress-nginx/namespace.yaml
  - external-dns/namespace.yaml
  - workflow.yaml

configMapGenerator:
  - name: external-secrets
    behavior: merge
    disableNameSuffixHash: true
    files:
      - external-secrets/application.yaml
  - name: tailscale
    behavior: merge
    disableNameSuffixHash: true
    files:
      - tailscale/application.yaml
  - name: ingress-nginx
    behavior: merge
    disableNameSuffixHash: true
    files:
      - ingress-nginx/application.yaml
  - name: external-dns
    behavior: merge
    disableNameSuffixHash: true
    files:
      - external-dns/application.yaml

namespace: default