---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - external-secrets/namespace.yaml
  - tailscale/namespace.yaml
  - ingress-nginx/namespace.yaml
  - external-dns/namespace.yaml
  - workflow.yaml

configMapGenerator:
  - name: external-secrets
    options:
      disableNameSuffixHash: true
    namespace: default
    files:
      - external-secrets/application.yaml
  - name: tailscale
    options:
      disableNameSuffixHash: true
    namespace: default
    files:
      - tailscale/application.yaml
  - name: ingress-nginx
    options:
      disableNameSuffixHash: true
    namespace: default
    files:
      - ingress-nginx/application.yaml
  - name: external-dns
    options:
      disableNameSuffixHash: true
    namespace: default
    files:
      - external-dns/application.yaml