apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets/application.yaml
  - tailscale/application.yaml
  - ingress-nginx/application.yaml
  - external-dns/application.yaml