apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workflow.yaml

configMapGenerator:
  - name: external-secrets
    files:
      - external-secrets/application.yaml
  - name: tailscale
    files:
      - tailscale/application.yaml
  - name: ingress-nginx
    files:
      - ingress-nginx/application.yaml
  - name: external-dns
    files:
      - external-dns/application.yaml