---
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: wf-addons
  namespace: default
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  workflowSpec:
    steps:
      - name: apply-external-secrets
        type: apply-app
        properties:
          ref:
            name: external-secrets
            key: application.yaml
            type: configMap
      
      - name: suspend
        type: suspend
        timeout: 5m

      - name: apply-tailscale
        type: apply-app
        properties:
          ref:
            name: tailscale
            key: application.yaml
            type: configMap

      - name: suspend
        type: suspend
        timeout: 5m

      - name: apply-ingress-nginx
        type: apply-app
        properties:
          ref:
            name: ingress-nginx
            key: application.yaml
            type: configMap

      - name: suspend
        type: suspend
        timeout: 5m

      - name: apply-external-dns
        type: apply-app
        properties:
          ref:
            name: external-dns
            key: application.yaml
            type: configMap