apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ingress-nginx
  namespace: base
  labels:
    project: base
spec:
  components:
    - name: ingress-nginx
      type: helm
      properties:
        repoType: helm
        url: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        version: 4.12.1
        namespace: ingress-nginx
        values:
          controller:
            service:
              type: LoadBalancer
              loadBalancerClass: tailscale

  policies:
  - name: ingress-nginx-local
    properties:
      clusters:
      - local
      namespace: ingress-nginx
    type: topology
  - name: ingress-nginx-sampa
    properties:
      clusters:
      - sampa
      namespace: ingress-nginx
    type: topology
    
  workflow:
    steps:
    - meta:
        alias: Deploy To ingress-nginx-local
      name: ingress-nginx-local
      properties:
        policies:
        - ingress-nginx-local
      type: deploy
    - meta:
        alias: Deploy To ingress-nginx-sampa
      name: ingress-nginx-sampa
      properties:
        policies:
        - ingress-nginx-sampa
      type: deploy