apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: miniflux-app
  namespace: miniflux
spec:
  project: miniflux
  components:
    - name: miniflux-admin
      type: raw
      properties:
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: miniflux-admin
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: infisical
          target:
            name: miniflux-admin
          data:
            - secretKey: username
              remoteRef:
                key: miniflux_admin_username
            - secretKey: password
              remoteRef:
                key: miniflux_admin_password
            - secretKey: database_url
              remoteRef:
                key: miniflux_database_url

    - name: miniflux
      type: webservice
      dependsOn:
        - miniflux-admin
      properties:
        image: docker.io/miniflux/miniflux:2.2.8
        port: 8080
        env:
          - name: RUN_MIGRATIONS
            value: "1"
          - name: CREATE_ADMIN
            value: "1"
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: username
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: database_url

      traits:
        - type: gateway
          properties:
            class: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            domain: news.tao.tec.br
            http:
              /: 8080

  policies:
    - name: miniflux-app-sampa
      properties:
        clusters:
          - sampa
        namespace: miniflux
      type: topology

  workflow:
    steps:
      - meta:
          alias: Deploy To miniflux-app-sampa
        name: miniflux-app-sampa
        properties:
          policies:
            - miniflux-app-sampa
        type: deploy
