apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: miniflux
spec:
  components:
    - name: miniflux-admin
      type: raw
      properties:
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: miniflux-admin
        spec:
          refreshInterval: 0.03m
          secretStoreRef:
            kind: ClusterSecretStore
            name: oracle
          target:
            name: miniflux-admin
            creationPolicy: Owner
          data:
            - secretKey: username
              remoteRef:
                key: miniflux_username
            - secretKey: password
              remoteRef:
                key: miniflux_password
            - secretKey: database_url
              remoteRef:
                key: miniflux_database_url

    - name: miniflux
      type: webservice
      properties:
        image: docker.io/miniflux/miniflux:2.2.8
        port: 8080
        env:
          - name: RUN_MIGRATIONS
            value: "1"
          - name: CREATE_ADMIN
            value: "1"
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: username
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: miniflux-admin
                key: database_url

      traits:
        - type: gateway
          properties:
            class: nginx
            domain: news.tao.tec.br
            http:
              /: 8080