---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
resources:
  - workflow.yaml

configMapGenerator:
  - name: db
    options:
      disableNameSuffixHash: true
    files:
      - db.yaml
  - name: app
    options:
      disableNameSuffixHash: true
    files:
      - app.yaml