---
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: wf-miniflux
  namespace: miniflux
  annotations:
    workflowrun.oam.dev/debug: "true"
    app.oam.dev/source-of-truth: from-velaux
    app.oam.dev/workflowName: workflow-miniflux
    app.oam.dev/publishVersion: workflow-miniflux-1
    app.oam.dev/deployVersion: "1"
spec:
  workflowSpec:
    steps:
      - name: apply-db
        type: apply-app
        properties:
          ref:
            name: db
            key: db.yaml
            type: configMap

      - name: apply-app
        type: apply-app
        dependsOn:
          - apply-db
        properties:
          ref:
            name: app
            key: app.yaml
            type: configMap
