apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  components:
    - name: ingress-nginx
      type: helm
      properties:
        repoType: helm
        url: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        version: 4.12.1
        namespace: ingress-nginx
        values:
          controller:
            service:
              type: LoadBalancer
              loadBalancerClass: tailscale