---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: base
resources:
  - workflow.yaml

configMapGenerator:
  - name: external-secrets
    options:
      disableNameSuffixHash: true
    files:
      - external-secrets/application.yaml
  - name: tailscale
    options:
      disableNameSuffixHash: true
    files:
      - tailscale/application.yaml
  - name: ingress-nginx
    options:
      disableNameSuffixHash: true
    files:
      - ingress-nginx/application.yaml
  - name: external-dns
    options:
      disableNameSuffixHash: true
    files:
      - external-dns/application.yaml
  - name: cert-manager
    options:
      disableNameSuffixHash: true
    files:
      - cert-manager/application.yaml