---
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: wf-base
  namespace: base
  annotations:
    workflowrun.oam.dev/debug: "true"
    app.oam.dev/source-of-truth: from-velaux
    app.oam.dev/workflowName: workflow-base
    app.oam.dev/publishVersion: workflow-base-3
    app.oam.dev/deployVersion: "3"
  labels:
    project: base
spec:
  workflowSpec:
    steps:
      - name: apply-external-secrets
        type: apply-app
        properties:
          ref:
            name: external-secrets
            key: application.yaml
            type: configMap

      - name: apply-tailscale
        type: apply-app
        dependsOn:
          - apply-external-secrets
        properties:
          ref:
            name: tailscale
            key: application.yaml
            type: configMap

      - name: apply-ingress-nginx
        type: apply-app
        dependsOn:
          - apply-tailscale
        properties:
          ref:
            name: ingress-nginx
            key: application.yaml
            type: configMap

      - name: apply-external-dns
        type: apply-app
        dependsOn:
          - apply-external-secrets
          - apply-ingress-nginx
        properties:
          ref:
            name: external-dns
            key: application.yaml
            type: configMap

      - name: apply-cert-manager
        type: apply-app
        dependsOn:
          - apply-external-secrets
        properties:
          ref:
            name: cert-manager
            key: application.yaml
            type: configMap

      - name: apply-monitoring-tools
        type: apply-app
        properties:
          ref:
            name: monitoring
            key: application-tools.yaml
            type: configMap

      - name: apply-monitoring-sampa
        type: apply-app
        properties:
          ref:
            name: monitoring
            key: application-sampa.yaml
            type: configMap